// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A tool for generating descriptions for various types of content.
 * 
 * - generateDescriptions - A function that handles the generation of descriptions.
 * - GenerateDescriptionsInput - The input type for the generateDescriptions function.
 * - GenerateDescriptionsOutput - The return type for the generateDescriptions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateDescriptionsInputSchema = z.object({
  topic: z.string().describe('The topic of the content.'),
  platform: z.string().describe('The platform for which the description is being generated (e.g., YouTube, Instagram, TikTok).'),
  keywords: z.string().optional().describe('Keywords to include in the description.'),
  tone: z.string().describe('The desired tone of the description (e.g., professional, funny, informative).'),
  context: z.string().optional().describe('Additional context or information to inform the description generation.'),
});
export type GenerateDescriptionsInput = z.infer<typeof GenerateDescriptionsInputSchema>;

const GenerateDescriptionsOutputSchema = z.object({
  description: z.string().describe('The generated description.'),
});
export type GenerateDescriptionsOutput = z.infer<typeof GenerateDescriptionsOutputSchema>;

export async function generateDescriptions(input: GenerateDescriptionsInput): Promise<GenerateDescriptionsOutput> {
  return generateDescriptionsFlow(input);
}

const generateDescriptionsPrompt = ai.definePrompt({
  name: 'generateDescriptionsPrompt',
  input: {schema: GenerateDescriptionsInputSchema},
  output: {schema: GenerateDescriptionsOutputSchema},
  prompt: `You are an expert copywriter specializing in creating engaging descriptions for various platforms.

  Generate a compelling description for the following content:

  Topic: {{{topic}}}
  Platform: {{{platform}}}
  Keywords: {{{keywords}}}
  Tone: {{{tone}}}

  Additional Context: {{{context}}}

  Description:`, // Ensure this is valid Handlebars syntax
});

const generateDescriptionsFlow = ai.defineFlow(
  {
    name: 'generateDescriptionsFlow',
    inputSchema: GenerateDescriptionsInputSchema,
    outputSchema: GenerateDescriptionsOutputSchema,
  },
  async input => {
    const {output} = await generateDescriptionsPrompt(input);
    return output!;
  }
);
